version: "3.5"

services: 
  test:
    build: ./test
    image: test_api
    restart: always
    container_name: test
    external_links:
      - exchanges_api
      - bots_api
    networks:
      - titan_backend  
    volumes:
      - ./bots/api:/usr/src/app/bots:delegated
      - ./exchanges/api:/usr/src/app/exchanges:delegated
      - ./utils:/usr/src/app/utils:delegated
      - ./postgres/connection/databaseManager.js:/usr/src/app/utils/databaseManager.js:delegated
      - ./postgres/connection/db.js:/usr/src/app/utils/db.js:delegated

networks:
  titan_backend:
    external: true