version: "3.5"

services:
  test:
    build: ./test
    image: test_api
    restart: always
    container_name: test
    external_links:
      - exchanges_api
      - bots_api
    networks:
      - goatFish_backend
    volumes:
      - ./bots/api:/usr/src/app/bots:delegated
      - ./exchanges/api:/usr/src/app/exchanges:delegated
      - utils_test:/usr/src/app/utils:delegated
      - database_test:/usr/src/app/utils/database:delegated

volumes:
  database_test:
    name: database
    driver: local
    driver_opts:
      type: none
      device: "$PWD/utils/database"
      o: bind
  utils_test:
    name: utils
    driver: local
    driver_opts:
      type: none
      device: "$PWD/utils"
      o: bind

networks:
  goatFish_backend:
    external: true
