name: CI/CD for project
on:
  push:
    branches:
      - master
  watch:
    types: [started]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: (echo yes; echo yes) | make test
        
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: src/coverage/lcov.info
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          path: src/bot_manager/api
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: lucasxhy/bot_manager
          tags: latest
          tag_with_sha: true
